# Generated by Django 5.0.8 on 2025-10-26 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("products", "0002_product_ean"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_note_number", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                (
                    "carrier",
                    models.CharField(
                        blank=True, help_text="Nome del corriere", max_length=200
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, help_text="Numero tracciamento", max_length=200
                    ),
                ),
                (
                    "packages_count",
                    models.PositiveIntegerField(
                        default=1, help_text="Numero di colli spediti"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="delivery_notes/%Y/%m/"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_notes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_note",
                        to="core.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bolla di Consegna",
                "verbose_name_plural": "Bolle di Consegna",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItemVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                (
                    "verified_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="Quantità effettivamente verificata"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Problemi o note sulla verifica"
                    ),
                ),
                (
                    "order_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification",
                        to="core.orderitem",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Verifica Articolo",
                "verbose_name_plural": "Verifiche Articoli",
            },
        ),
        migrations.CreateModel(
            name="OrderNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                (
                    "is_important",
                    models.BooleanField(
                        default=False, help_text="Contrassegna come importante"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_notes",
                        to="core.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota Ordine",
                "verbose_name_plural": "Note Ordini",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderProcessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_prepare", "Da Preparare"),
                            ("preparing", "In Preparazione"),
                            ("ready", "Pronto per la Spedizione"),
                            ("shipped", "Spedito"),
                            ("delivered", "Consegnato"),
                            ("cancelled", "Annullato"),
                        ],
                        default="to_prepare",
                        max_length=20,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Quando è iniziata la preparazione",
                        null=True,
                    ),
                ),
                (
                    "ready_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Quando è pronto per la spedizione",
                        null=True,
                    ),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(
                        blank=True, help_text="Quando è stato spedito", null=True
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, help_text="Quando è stato consegnato", null=True
                    ),
                ),
                (
                    "items_verified",
                    models.BooleanField(
                        default=False, help_text="Articoli verificati in magazzino"
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, help_text="Note interne per lo staff"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Operatore assegnato alla preparazione",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing",
                        to="core.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processo Ordine",
                "verbose_name_plural": "Processi Ordini",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("out", "Uscita (Vendita)"),
                            ("in", "Entrata (Reso/Annullamento)"),
                            ("adjustment", "Rettifica"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Quantità movimentata (positivo o negativo)"
                    ),
                ),
                (
                    "stock_before",
                    models.IntegerField(help_text="Stock prima del movimento"),
                ),
                (
                    "stock_after",
                    models.IntegerField(help_text="Stock dopo il movimento"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="core.order",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="core.orderitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimento Magazzino",
                "verbose_name_plural": "Movimenti Magazzino",
                "ordering": ["-created_at"],
            },
        ),
    ]
