# Generated by Django 5.2.7 on 2025-10-09 14:57

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_ean'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='cart', unique=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Sessione')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Carrello',
                'verbose_name_plural': 'Carrelli',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGH12345', length=10, max_length=20, prefix='ORD', unique=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('shipping_address', models.TextField(verbose_name='Indirizzo di Spedizione')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='Città')),
                ('shipping_state', models.CharField(max_length=100, verbose_name='Provincia')),
                ('shipping_postal_code', models.CharField(max_length=20, verbose_name='CAP')),
                ('shipping_country', models.CharField(default='Italia', max_length=100, verbose_name='Paese')),
                ('billing_address', models.TextField(blank=True, verbose_name='Indirizzo di Fatturazione')),
                ('billing_city', models.CharField(blank=True, max_length=100, verbose_name='Città')),
                ('billing_state', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('billing_postal_code', models.CharField(blank=True, max_length=20, verbose_name='CAP')),
                ('billing_country', models.CharField(blank=True, max_length=100, verbose_name='Paese')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Subtotale')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Costo Spedizione')),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Totale')),
                ('order_status', models.CharField(choices=[('pending', 'In Attesa'), ('processing', 'In Elaborazione'), ('shipped', 'Spedito'), ('delivered', 'Consegnato'), ('cancelled', 'Annullato'), ('refunded', 'Rimborsato')], default='pending', max_length=20, verbose_name='Stato Ordine')),
                ('order_notes', models.TextField(blank=True, verbose_name='Note Ordine')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Ordine',
                'verbose_name_plural': 'Ordini',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200, verbose_name='Nome Prodotto')),
                ('product_sku', models.CharField(max_length=20, verbose_name='SKU')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantità')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prezzo Unitario')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order', verbose_name='Ordine')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Prodotto')),
            ],
            options={
                'verbose_name': 'Articolo Ordine',
                'verbose_name_plural': 'Articoli Ordine',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGH12345', length=10, max_length=20, prefix='PAY', unique=True)),
                ('payment_method', models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Carta di Credito/Debito'), ('bank_transfer', 'Bonifico Bancario'), ('cash_on_delivery', 'Contrassegno')], max_length=20, verbose_name='Metodo di Pagamento')),
                ('payment_status', models.CharField(choices=[('pending', 'In Attesa'), ('processing', 'In Elaborazione'), ('completed', 'Completato'), ('failed', 'Fallito'), ('refunded', 'Rimborsato')], default='pending', max_length=20, verbose_name='Stato Pagamento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Importo')),
                ('transaction_id', models.CharField(blank=True, max_length=200, verbose_name='ID Transazione')),
                ('paypal_order_id', models.CharField(blank=True, max_length=200, verbose_name='PayPal Order ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200, verbose_name='Stripe Payment Intent ID')),
                ('payment_response', models.JSONField(blank=True, default=dict, verbose_name='Risposta Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pagato il')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.order', verbose_name='Ordine')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamenti',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantità')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prezzo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Aggiunto il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cart', verbose_name='Carrello')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Prodotto')),
            ],
            options={
                'verbose_name': 'Articolo Carrello',
                'verbose_name_plural': 'Articoli Carrello',
                'ordering': ['-created_at'],
                'unique_together': {('cart', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Pessimo'), (2, '2 - Scarso'), (3, '3 - Sufficiente'), (4, '4 - Buono'), (5, '5 - Eccellente')], verbose_name='Valutazione')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo')),
                ('comment', models.TextField(verbose_name='Commento')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approvata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creata il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornata il')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='Prodotto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Recensione',
                'verbose_name_plural': 'Recensioni',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Aggiunto il')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Prodotto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Lista Desideri',
                'verbose_name_plural': 'Liste Desideri',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
