# Generated by Django 5.2.7 on 2025-10-08 12:23

import django.db.models.deletion
import django_ckeditor_5.fields
import products.models
import shortuuid.django_fields
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '__latest__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='cat', unique=True)),
                ('title', models.CharField(default='Categoria', max_length=100, verbose_name='Nome')),
                ('image', models.ImageField(default='category.jpg', upload_to='category', verbose_name='Immagine')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='', unique=True)),
                ('title', models.CharField(default='Prodotto', max_length=100, verbose_name='Nome')),
                ('image', models.ImageField(default='product.jpg', upload_to=products.models.user_directory_path, verbose_name='Immagine')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Descrizione')),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=12, verbose_name='Prezzo')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=12, null=True, verbose_name='Prezzo precedente')),
                ('stock_count', models.IntegerField(default=0, verbose_name='Quantità disponibile')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso (kg)')),
                ('product_status', models.CharField(choices=[('draft', 'Draft'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('published', 'Published')], default='in_review', max_length=10, verbose_name='Stato')),
                ('status', models.BooleanField(default=True, verbose_name='Attivo')),
                ('in_stock', models.BooleanField(default=True, verbose_name='Disponibile')),
                ('featured', models.BooleanField(default=False, verbose_name='In evidenza')),
                ('digital', models.BooleanField(default=False, verbose_name='Prodotto digitale')),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=4, max_length=10, prefix='sku', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Ultima modifica')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Categoria')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
            ],
            options={
                'verbose_name': 'Prodotto',
                'verbose_name_plural': 'Prodotti',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='product.jpg', upload_to='product-images', verbose_name='Immagine')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data caricamento')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_images', to='products.product', verbose_name='Prodotto')),
            ],
            options={
                'verbose_name': 'Immagine Prodotto',
                'verbose_name_plural': 'Immagini Prodotto',
                'ordering': ['-date'],
            },
        ),
    ]
