# Generated by Django 5.2.7 on 2025-10-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, help_text='Codice a barre europeo (13 cifre)', max_length=13, null=True, unique=True, verbose_name='Codice EAN'),
        ),
    ]
